### PR TITLE
Correct host_endpoint{_id} tapi docs

### LINKED ISSUE #61: Transfer API doc error: shared endpoint creation doesn't state requirement for `host_endpoint`
@corpulentcoffee I'd like you to confirm that I'm not seeing strange behavior, and that this is consistent with your experience with the API.
We state `host_endpoint_id` as a part of Shared Endpoint documents, but if I send one with that, rather than `host_endpoint`, the API gives back

```
HTTP status:      400
request_id:       b8cLb48tQ
code:             BadRequest
message:          Bad JSON Data: Field 'host_endpoint' not found
```

There's a bug here (which I'll file against Transfer) because that field should be translated/respected, but I don't know if that will make it into the current release.
The docs need fixing in the meantime.

I'm still not quite sure where the change is necessary.
Amending the description of a shared endpoint doc seems like poor form, since we're supposed to be _deprecating_ `host_endpoint` as a field.
I think I'll put it in as a warning blob here: https://docs.globus.org/api/transfer/endpoint/#create_shared_endpoint

### PR DESCRIPTION
**Pull request by sirosen**
Transfer API documentation needs to specify `host_endpoint` on POST/PUT and `host_endpoint_id` on GET.

Resolves #61

### CODE REVIEW

**Comment by karlito-go** [comment]
the transfer docs are in koa, they are just copied to this repo during build.

This is a mess.  But thanks to the magic blessings of REST-API design https://github.com/globusonline/koa/blob/master/tapi/globus_org_rest/model/endpoint.py#L372-L528 it's just not going to be touched, ever.  So thanks for just doing a doc change.  I'll add it to the koa docs.

**Comment by sirosen** [comment]
Thanks for taking a look; I hadn't realized that the changes should flow into koa first.

Amended this commit to match your changes.

**Comment by teresas** [comment]
Should I merge this in from the PR or pull the updated content from the koa repo? Have other updates been made in the koa repo that we might want to include? If so, what branch would it be good to pull from?

**Comment by karlito-go** [comment]
teresas - you can just merge this PR if you want.  nothing else has changed in koa master yet.

**Pull request merged**
