### PR TITLE
Separate Legacy CLI docs from current CLI

### PR DESCRIPTION
**Pull request by sirosen**
Legacy CLI docs should not render current docs unreadable. Separate, correct minor errors, and refactor documentation to handle the separation.
Designates the legacy docs as `in_menu: false`

In my local runs, even though the legacy docs have `in_menu: false`, they appear in the sidebar. If there's an easy explanation or fix, I'd like to know.
Most probably this will have to pass through review on Staging, but I'm opening the PR against `prod` because that's the destination for these changes post-review. I'm happy to push a branch on the original repo or do anything else which facilitates review.

### CODE REVIEW

**Comment by sirosen** [comment]
Oh, and of course this closes #192. That bears saying.

**Comment by sirosen** [comment]
Per feedback from Rachana, I've modified some text, dropped the `in_menu: false` directives (we want the hosted CLI in the sidebar), and reviewed/updated the FAQ content.

I've also relocated the legacy/hosted CLI reference material from `cli/hosted/` to `cli/legacy/reference` to map nicely with the current man pages at `cli/reference`

Additionally fixes some commands from reading like `task show` to _always_ read as `globus task show`.
This is currently on docs.staging.globuscs.info, and I'll be asking for review from Vas, Greg, and final signoff by Rachana.

**Comment by vasv** [comment]
Reviewed - looks good to me. Thanks for doing.

- Vas

**Comment by globusgreg** [comment]
I concur - looks good to me as well. Thanks.
-- Greg

**Comment by sirosen** [comment]
Woah, this has a ton of errors then... I'll take another pass over this soon, and try to be more thorough in examining the results

**Comment by sirosen** [comment]
I've updated with the requested fixes.

Also, the change to `faq/subscriptions` may be a little confusing. bde17e4 actually removed those `NOTE` blocks -- after other updates they became irrelevant.

**Pull request merged**
